server {
    listen 80;

    location / {
        proxy_pass http://dashboard:3000;
    }

    location /api/ {
        proxy_pass http://gateway:3000;
    }

    location /health {
        proxy_pass http://gateway:3000;
    }
}
