'use client';
import { FormEvent, useState } from 'react';
import { apiRequest, AwsConnection } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { useWorkspace } from './workspace';
import { accountName, formatDate } from '@/lib/presentation';
import { Badge, Button, Dialog, EmptyState, Field, Icon, Loading, Notice, PageHeading, Panel } from './primitives';
export default function Accounts() {
  const { connections, reports, system, refresh, loading } = useWorkspace(); const { token } = useAuth();
  const [connecting, setConnecting] = useState(false); const [externalId, setExternalId] = useState(''); const [arn, setArn] = useState(''); const [label, setLabel] = useState(''); const [region, setRegion] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [disconnect, setDisconnect] = useState<AwsConnection | null>(null);
  if (loading) return <Loading/>;
  const setupUrl = system?.template_url && system.trusted_principal_arn ? `https://console.aws.amazon.com/cloudformation/home#/stacks/create/review?${new URLSearchParams({ templateURL: system.template_url, stackName: 'CloudSentinelScanRole', param_TrustedPrincipalArn: system.trusted_principal_arn, param_ExternalId: externalId })}` : null;
  function open() { setExternalId(crypto.randomUUID()); setArn(''); setLabel(''); setRegion(system?.region || 'us-east-1'); setError(''); setConnecting(true); }
  async function save(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    try { await apiRequest('/api/aws-connections', { method: 'POST', body: JSON.stringify({ role_arn: arn, label, external_id: externalId, region }) }, token!); await refresh(); setConnecting(false); }
    catch (err) { setError(err instanceof Error ? err.message : 'Unable to save connection'); } finally { setBusy(false); }
  }
  return <><PageHeading eyebrow="CLOUD INVENTORY" title="AWS accounts" description="Read-only access to the AWS accounts you own and operate." action={<Button onClick={open}><Icon name="plus"/>Connect account</Button>}/>
    <Notice>Connections use temporary AssumeRole sessions. Long-lived AWS credentials are never entered here. Access is verified when a scan runs; a saved connection is not automatically verified.</Notice>
    {error && !connecting && <Notice tone="error">{error}</Notice>}
    <Panel title="Worker identity" action={<Badge value="active"/>}><div className="connection-summary"><span className="account-icon"><Icon name="accounts" size={28}/></span><div><h3>Server-configured AWS identity</h3><p className="muted">Uses the AWS credential provider configured for the worker. Its account ID is recorded after a successful connection during scanning.</p></div><div className="mono">{system?.region || 'Not configured'}</div></div></Panel>
    <Panel title={`Connected accounts · ${connections.filter(c => c.active).length}`}>{connections.length ? <div className="table-scroll"><table><thead><tr><th>Account</th><th>Role</th><th>Default region</th><th>Connection</th><th>Last assessment</th><th/></tr></thead><tbody>{connections.map(c => {
      const last = reports.find(r => r.report.context?.connection_id === c.id);
      return <tr key={c.id}><td><strong>{accountName(c.id, connections)}</strong><small className="mono">{c.role_arn.split(':')[4]}</small></td><td className="mono break-word">{c.role_arn.split(':role/')[1]}</td><td className="mono">{c.region}</td><td><Badge value={c.active ? 'active' : 'paused'}/><small>{last ? 'Access observed during scan' : 'Not yet assessed'}</small></td><td>{formatDate(last?.created_at)}</td><td>{c.active && <Button variant="ghost" onClick={() => setDisconnect(c)}>Disconnect</Button>}</td></tr>;
    })}</tbody></table></div> : <EmptyState title="Connect your first AWS account" action={<Button variant="secondary" onClick={open}>Set up a read-only role</Button>}>Create a role with limited inspection permissions. Use the account selector when starting each scan.</EmptyState>}</Panel>
    {connecting && <Dialog title="Connect an AWS account" onClose={() => setConnecting(false)}><form onSubmit={save} className="dialog-body form-stack"><div className="setup-steps"><div><span>01</span><div><h3>Create a read-only role</h3>{setupUrl ? <a className="inline-link" href={setupUrl} target="_blank" rel="noreferrer">Open CloudFormation setup ↗</a> : <p>Use <code>infra/cloudformation/cloud-sentinel-scan-role.yaml</code> in your AWS account. Configure the trusted worker principal on the server to enable the guided setup link.</p>}</div></div><div><span>02</span><div><h3>Use a unique External ID</h3><p>The setup link includes a per-connection External ID. For manual setup, copy it into the template parameter.</p><Button variant="secondary" onClick={async () => { try { await navigator.clipboard.writeText(externalId); } catch { setError('Clipboard unavailable. Use HTTPS or the guided setup link.'); } }}>Copy setup External ID</Button></div></div><div><span>03</span><div><h3>Save the role from stack outputs</h3><p>Only role configuration is saved. Temporary AWS session credentials stay in the worker.</p></div></div></div>
      <Field label="Connection name"><input required maxLength={80} value={label} onChange={e => setLabel(e.target.value)} placeholder="Production account"/></Field><Field label="IAM role ARN"><input required value={arn} onChange={e => setArn(e.target.value)} placeholder="arn:aws:iam::123456789012:role/CloudSentinelScanRole"/></Field><Field label="Default scan region"><input required value={region} onChange={e => setRegion(e.target.value)}/></Field>{error && <Notice tone="error">{error}</Notice>}<div className="dialog-actions"><Button variant="secondary" onClick={() => setConnecting(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save connection'}</Button></div>
    </form></Dialog>}
    {disconnect && <Dialog title="Disconnect AWS account" onClose={() => setDisconnect(null)}><div className="dialog-body form-stack"><p>Disconnect <strong>{accountName(disconnect.id, connections)}</strong>? Its schedules will be paused. Pending scans will fail safely instead of switching to another account. Historical reports are preserved.</p><p className="muted">An already running scan may finish using its temporary session. Remove the IAM role in AWS to revoke future role access.</p><div className="dialog-actions"><Button variant="secondary" onClick={() => setDisconnect(null)}>Keep connection</Button><Button variant="danger" disabled={busy} onClick={async () => { setBusy(true); try { await apiRequest(`/api/aws-connections/${disconnect.id}`, { method: 'DELETE' }, token!); await refresh(); setDisconnect(null); } catch (err) { setError(String(err)); setDisconnect(null); } finally { setBusy(false); } }}>Disconnect</Button></div></div></Dialog>}
  </>;
}
