'use client';
import Link from 'next/link';
import { useWorkspace } from './workspace';
import { Badge, EmptyState, Icon, Loading, PageHeading, Panel } from './primitives';
import { compatibleReports, formatDate, reportScope, shortId, statusOf } from '@/lib/presentation';
import { SeverityChart, TrendChart } from './charts';
import { ScopeNotice, StartScanButton } from './shell';
export function useScopedData() {
  const data = useWorkspace();
  const matches = (id: number | null | undefined) => data.selectedConnection === 'all' || data.selectedConnection === 'worker' && id === null || String(id) === data.selectedConnection;
  return { ...data, reports: data.reports.filter(r => data.selectedConnection === 'all' || r.report.context && matches(r.report.context.connection_id)), tasks: data.tasks.filter(t => matches(t.connection_id)) };
}
export default function Overview() {
  const { reports, tasks, schedules, system, loading } = useScopedData();
  if (loading) return <Loading/>;
  const latest = reports[0]; const report = latest?.report;
  const failed = report?.findings.filter(f => statusOf(f) === 'FAIL' && f.category !== 'Correlated') || [];
  const active = tasks.filter(t => t.status === 'running' || t.status === 'queued');
  const enabled = schedules.filter(s => s.enabled);
  return <><PageHeading eyebrow="SECURITY OPERATIONS" title="Security overview" description="Your cloud posture. Evidence first, action next." action={<span className="page-date">{new Date().toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</span>}/><ScopeNotice/>
    <div className="metrics-grid"><div className="metric"><span>Critical findings</span><strong className={failed.some(f => f.severity === 'critical') ? 'text-critical' : ''}>{report ? failed.filter(f => f.severity === 'critical').length : '—'}</strong><small>Observed in latest assessment</small></div><div className="metric"><span>Failed checks</span><strong>{report ? failed.length : '—'}</strong><small>{report?.check_summary ? `${report.check_summary.pass} passed · ${report.check_summary.unknown} unknown` : 'Awaiting an assessment'}</small></div><div className="metric"><span>Scans in progress</span><strong>{active.length}<span className="metric-unit">active</span></strong><small>{active.length ? 'Tracked across navigation and reloads' : 'No scans currently queued or running'}</small></div><div className="metric"><span>Scheduled protection</span><strong>{enabled.length}<span className="metric-unit">schedules</span></strong><small>{enabled.length ? 'Automatic checks are enabled' : 'Configure recurring assessments'}</small></div></div>
    {!latest ? <Panel><EmptyState title="Establish your security baseline" action={<StartScanButton/>}>Connect an AWS account or use the worker identity, choose a region, and run your first read-only assessment. Real findings will appear here.</EmptyState></Panel> : <>
    <div className="overview-grid"><Panel title="Security posture" action={<Badge value={report?.partial || !report?.context ? 'partial' : 'done'}/>}><div className="posture"><div className="score-block"><span className="score-number">{report?.risk_score ?? '—'}</span><span className="score-denominator">/ 100</span><div className="score-caption">{report?.risk_grade ? `Grade ${report.risk_grade}` : 'Not assessed'}{report?.score_provisional ? ' · provisional' : ''}</div></div><div className="posture-context"><span className="eyebrow">LATEST ASSESSMENT</span><strong>{report?.connection_label || 'Account scope unavailable'}</strong><span className="mono">{reportScope(latest)}</span><span>{formatDate(latest.created_at)}</span><Link className="inline-link" href={`/reports/${latest.id}`}>Inspect report <Icon name="arrow" size={15}/></Link></div></div><div className="panel-footnote">Higher is better. Score covers observed checks only; unknown evidence is never a pass.</div></Panel>
    <Panel title="Finding severity" action={<span className="small muted">Failed checks only</span>}><SeverityChart findings={report?.findings || []}/><div className="change-row"><div><strong>{report?.diff?.has_previous_scan ? report.diff.new_count : '—'}</strong><span>New</span></div><div><strong>{report?.diff?.has_previous_scan ? report.diff.resolved_count : '—'}</strong><span>Resolved</span></div><div><strong>{report?.diff?.has_previous_scan ? (report.diff.changed_count || 0) + (report.diff.severity_changed_count || 0) : '—'}</strong><span>Changed</span></div></div><div className="panel-footnote">Compared with the previous matching account and scan scope.</div></Panel></div>
    <div className="overview-grid"><Panel title="Posture over time" action={<span className="small muted">Comparable scans · higher is better</span>}><TrendChart reports={compatibleReports(reports, latest)}/></Panel><Panel title="Priority findings" action={<Link className="inline-link" href={`/findings?report=${latest.id}`}>View all <Icon name="arrow" size={14}/></Link>}>{failed.length ? <div className="priority-list">{failed.slice(0, 4).map((f, i) => <Link key={f.id || i} href={`/findings?report=${latest.id}&finding=${encodeURIComponent(f.id || '')}`}><span className={`priority-marker severity-${f.severity}`}/><div><strong>{f.title || f.type}</strong><span className="mono">{f.resource}</span></div><Icon name="arrow" size={15}/></Link>)}</div> : <div className="compact-empty">No failed checks were recorded. Review report coverage for unknown or skipped checks.</div>}</Panel></div></>}
    <div className="overview-grid"><Panel title="Recent scan activity" action={<Link className="inline-link" href="/scans">All scans <Icon name="arrow" size={14}/></Link>}>{tasks.length ? <div className="table-scroll"><table><thead><tr><th>Scan</th><th>Started</th><th>State</th></tr></thead><tbody>{tasks.slice(0, 5).map(t => <tr key={t.task_id}><td className="mono">{t.report_id ? <Link href={`/reports/${t.report_id}`}>{shortId(t.task_id)}</Link> : shortId(t.task_id)}<small>{t.payload.region || 'Legacy scope'}</small></td><td>{formatDate(t.created_at)}</td><td><Badge value={t.status}/></td></tr>)}</tbody></table></div> : <div className="compact-empty">No scan activity yet.</div>}</Panel><Panel title="System readiness" action={system && <Badge value={system.status}/>}><div className="system-list">{['postgres', 'redis', 'worker'].map(service => <div key={service}><span className="service-label"><Icon name={service === 'worker' ? 'scans' : 'settings'} size={16}/>{service === 'postgres' ? 'PostgreSQL' : service === 'redis' ? 'Redis dispatch' : 'Scan worker'}</span><Badge value={system?.checks[service] || 'unknown'}/></div>)}</div><div className="panel-footnote">Worker status is based on its heartbeat. Scans remain durable if Redis is unavailable.</div></Panel></div>
  </>;
}
