'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiRequest, getAiSummary, ReportRow } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { formatDate, reportScope, shortId } from '@/lib/presentation';
import { useScopedData } from './overview';
import { useWorkspace } from './workspace';
import { Badge, Button, EmptyState, Loading, Notice, PageHeading, Panel } from './primitives';
import { FindingsTable } from './findings';
import { SeverityChart } from './charts';
export default function Reports() {
  const { reports, loading } = useScopedData(); if (loading) return <Loading/>;
  return <><PageHeading eyebrow="EVIDENCE LIBRARY" title="Reports" description="Immutable assessment snapshots, with explicit scope and coverage."/><Panel>{reports.length ? <div className="table-scroll"><table><thead><tr><th>Report</th><th>Account / region</th><th>Score</th><th>Coverage</th><th>Checks</th><th>Completed</th></tr></thead><tbody>{reports.map(row => <tr key={row.id}><td><Link className="table-link" href={`/reports/${row.id}`}>Assessment #{row.id} →</Link><small className="mono">{shortId(row.report.task_id)}</small></td><td>{row.report.connection_label || 'Legacy report'}<small className="mono">{reportScope(row)}</small></td><td><strong>{row.report.risk_score ?? '—'}</strong><small>{row.report.risk_grade ? `Grade ${row.report.risk_grade}${row.report.score_provisional ? ' · provisional' : ''}` : 'Not scored'}</small></td><td><Badge value={!row.report.context || row.report.partial ? 'partial' : 'done'}/></td><td>{row.report.check_summary ? `${row.report.check_summary.fail} fail / ${row.report.check_summary.pass} pass` : 'Not recorded'}<small>{row.report.check_summary?.unknown ?? '—'} unknown</small></td><td>{formatDate(row.created_at)}</td></tr>)}</tbody></table></div> : <EmptyState title="No reports yet">Completed and partially completed assessments will be preserved here.</EmptyState>}</Panel></>;
}
function AiInsights({ row }: { row: ReportRow }) {
  const { token } = useAuth(); const { system } = useWorkspace();
  const [summary, setSummary] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <Panel title="AI-assisted interpretation" action={<span className="small muted">Optional · Gemini</span>}><div className="panel-body">{!system?.ai_configured ? <p className="muted">AI insights are not configured. All scanner evidence, findings, and remediation remain available.</p> : <><p className="muted">Generate a prioritized interpretation. Report contents are sent to Gemini; AI output is separate from verified scanner evidence.</p><Button variant="secondary" disabled={busy} onClick={async () => { if (!token) return; setBusy(true); setError(''); try { const data = await getAiSummary(token, row.id); setSummary(data.summary); } catch (err) { setError(err instanceof Error ? err.message : 'AI unavailable'); } finally { setBusy(false); } }}>{busy ? 'Generating insights…' : summary ? 'Regenerate insights' : 'Generate insights'}</Button>{error && <Notice tone="error">{error}</Notice>}{summary && <div className="ai-result"><div className="eyebrow">AI-GENERATED · REVIEW AGAINST EVIDENCE</div><p>{summary}</p></div>}</>}</div></Panel>;
}
export function ReportDetail({ id }: { id: string }) {
  const { reports } = useWorkspace(); const { token } = useAuth();
  const existing = reports.find(r => String(r.id) === id); const [fetched, setFetched] = useState<ReportRow | null>(null); const [error, setError] = useState('');
  useEffect(() => { let ignore = false; setError(''); setFetched(null); if (!existing && token) apiRequest<ReportRow>(`/api/reports/${encodeURIComponent(id)}`, {}, token).then(r => { if (!ignore) setFetched(r); }).catch(err => { if (!ignore) setError(err.message); }); return () => { ignore = true; }; }, [id, existing, token]);
  const row = existing || fetched;
  if (error) return <Notice tone="error">{error} <Link href="/reports">Back to reports</Link></Notice>;
  if (!row) return <Loading/>;
  const report = row.report;
  function download() { const url = URL.createObjectURL(new Blob([JSON.stringify(row, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `cloud-sentinel-report-${id}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <><Link className="back-link" href="/reports">← All reports</Link><PageHeading eyebrow="ASSESSMENT REPORT" title={`Assessment #${row.id}`} description={`${report.connection_label || 'Legacy assessment'} · ${formatDate(row.created_at)}`} action={<div className="badge-row"><Button variant="secondary" onClick={download}>Export JSON</Button><Button variant="secondary" onClick={() => window.print()}>Print report</Button></div>}/>
    <Notice tone={report.partial || !report.context ? 'warning' : 'info'}>{report.assessment_note || 'Legacy report: account, region and check coverage were not recorded. Run a new scan for an explicit assessment.'}{report.partial && ' This report is partial: some evidence could not be obtained.'}</Notice>
    <Panel><dl className="report-metadata"><div><dt>Scan ID</dt><dd className="mono">{shortId(report.task_id)}</dd></div><div><dt>AWS account</dt><dd className="mono">{report.context?.account_id || 'Not recorded'}</dd></div><div><dt>Region / mode</dt><dd>{report.context ? `${report.context.region} / ${report.context.mode}` : 'Not recorded'}</dd></div><div><dt>Services</dt><dd>{report.context?.services.join(', ') || 'Not recorded'}</dd></div><div><dt>Duration</dt><dd>{report.duration_sec !== undefined ? `${report.duration_sec}s` : 'Not recorded'}</dd></div></dl></Panel>
    <div className="metrics-grid">{(['pass', 'fail', 'skipped', 'unknown'] as const).map(state => <div className="metric" key={state}><Badge value={state.toUpperCase()}/><strong>{report.check_summary?.[state] ?? '—'}</strong><small>{state === 'unknown' ? 'Unavailable evidence; not a pass' : state === 'skipped' ? 'Not applicable or not evaluated' : 'Resource-level checks; excludes correlations'}</small></div>)}</div>
    <div className="overview-grid"><Panel title="Observed security score"><div className="panel-body"><div className="score-inline"><strong>{report.risk_score ?? '—'}</strong><span>/ 100 {report.risk_grade && `· Grade ${report.risk_grade}`}</span></div><p className="muted">{report.score_provisional ? 'Provisional score: unknown checks remain.' : 'Score applies only to assessed checks.'} Penalties: critical 15, medium 5, low 1. Related-risk annotations are not counted twice.</p><SeverityChart findings={report.findings}/></div></Panel><Panel title="Scope and benchmark evidence"><div className="coverage-list">{report.coverage?.map(c => <div key={c.service}><span><strong>{c.service.toUpperCase()}</strong><small>{c.region} · {c.checks} observations</small></span><Badge value={c.status === 'UNKNOWN' ? 'UNKNOWN' : 'done'}/></div>) || <p className="muted">Coverage not recorded.</p>}</div>{report.cis_summary && <div className="panel-footnote">{report.cis_summary.controls_passing} passing / {report.cis_summary.controls_assessed} observed CIS control groups. {report.cis_summary.note || 'Partial benchmark evidence only.'}</div>}</Panel></div>
    {report.diff?.has_previous_scan && <Notice>{report.diff.new_count} new · {report.diff.resolved_count} resolved · {(report.diff.changed_count || 0) + (report.diff.severity_changed_count || 0)} changed · {report.diff.unobserved_count || 0} no longer observable. Comparison uses the previous matching account and scope.</Notice>}
    <Panel title="Assessment evidence"><FindingsTable findings={report.findings}/></Panel>{!!report.diff?.resolved_findings?.length && <Panel title="Previously failed · now resolved"><FindingsTable findings={report.diff.resolved_findings.map(f => ({ ...f, status: 'PASS', change: 'resolved', description: 'Resolved in this comparison. Previous evidence: ' + (f.description || ''), details: 'Resolved in this comparison. Previous evidence: ' + (typeof f.details === 'string' ? f.details : f.description || '') }))}/></Panel>}
    <AiInsights key={row.id} row={row}/>
  </>;
}
