'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { apiRequest, Schedule } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { accountName, formatDate } from '@/lib/presentation';
import { useWorkspace } from './workspace';
import { ScopeFields, useDefaultScope } from './scan-form';
import { Badge, Button, Dialog, EmptyState, Field, Icon, Loading, Notice, PageHeading, Panel } from './primitives';
export default function Schedules() {
  const { schedules, connections, refresh, loading } = useWorkspace(); const { token } = useAuth();
  const defaults = useDefaultScope(); const [input, setInput] = useState(defaults); const [hours, setHours] = useState(24); const [open, setOpen] = useState(false); const [remove, setRemove] = useState<Schedule | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (loading) return <Loading/>;
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await apiRequest('/api/schedules', { method: 'POST', body: JSON.stringify({ ...input, interval_hours: hours }) }, token!); await refresh(); setOpen(false); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create schedule'); } finally { setBusy(false); } }
  function begin() { setInput(defaults); setError(''); setOpen(true); }
  return <><PageHeading eyebrow="AUTOMATION" title="Schedules" description="Repeatable security checks, bound to an explicit account and scope." action={<Button onClick={begin}><Icon name="plus"/>Create schedule</Button>}/>
    {error && !open && <Notice tone="error">{error}</Notice>}<Panel>{schedules.length ? <div className="table-scroll"><table><thead><tr><th>Target account</th><th>Scope</th><th>Frequency</th><th>Next run</th><th>Previous run</th><th>Status</th><th/></tr></thead><tbody>{schedules.map(s => <tr key={s.id}><td><strong>{s.mode === 'floci' ? 'Floci emulator' : accountName(s.connection_id, connections)}</strong><small className="mono">Schedule #{s.id}</small></td><td className="mono">{s.region}<small>{s.services.join(', ')}</small></td><td>Every {s.interval_hours}h</td><td>{s.enabled ? formatDate(s.next_run_at) : 'Paused'}</td><td>{formatDate(s.last_run_at)}{s.last_status && <small><Badge value={s.last_status}/></small>}{s.last_error && <small className="text-critical">{s.last_error}</small>}</td><td><Badge value={s.enabled ? 'active' : 'paused'}/></td><td><div className="row-actions"><Button variant="secondary" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await apiRequest(`/api/schedules/${s.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: !s.enabled }) }, token!); await refresh(); } catch (err) { setError(String(err)); } finally { setBusy(false); } }}>{s.enabled ? 'Pause' : 'Enable'}</Button><Button variant="ghost" disabled={busy} onClick={() => setRemove(s)}>Delete</Button></div></td></tr>)}</tbody></table></div> : <EmptyState title="Make security checks a routine" action={<Button variant="secondary" onClick={begin}>Create your first schedule</Button>}>Choose a connection, a region, and an interval. Each execution is recorded in scan history.</EmptyState>}</Panel>
    <Notice>Intervals run from the last dispatch time. Missed intervals are coalesced into one scan after downtime. Pausing a schedule does not cancel an already queued scan. <Link href="/scans">View scan activity →</Link></Notice>
    {open && <Dialog title="Create a scan schedule" onClose={() => setOpen(false)}><form onSubmit={create} className="dialog-body form-stack"><ScopeFields value={input} onChange={setInput}/><Field label="Run every (hours)" hint="1–168 hours. The first scan is queued after this interval."><input type="number" min={1} max={168} required value={hours} onChange={e => setHours(Number(e.target.value))}/></Field><div className="scan-confirmation"><span className="eyebrow">SCHEDULED TARGET</span><strong>{input.mode === 'floci' ? 'Floci emulator' : accountName(input.connection_id, connections)}</strong><span>{input.region} · every {hours} hours</span></div>{error && <Notice tone="error">{error}</Notice>}<div className="dialog-actions"><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={busy || !input.services.length}>{busy ? 'Creating…' : 'Create schedule'}</Button></div></form></Dialog>}
    {remove && <Dialog title="Delete schedule" onClose={() => setRemove(null)}><div className="dialog-body"><p>Delete schedule #{remove.id} for <strong>{accountName(remove.connection_id, connections)}</strong>? Existing scans and reports are preserved.</p><div className="dialog-actions"><Button variant="secondary" onClick={() => setRemove(null)}>Cancel</Button><Button variant="danger" disabled={busy} onClick={async () => { setBusy(true); try { await apiRequest(`/api/schedules/${remove.id}`, { method: 'DELETE' }, token!); await refresh(); setRemove(null); } catch (err) { setError(String(err)); setRemove(null); } finally { setBusy(false); } }}>Delete schedule</Button></div></div></Dialog>}
  </>;
}
